name: tiktok_clone
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0' # ✅ ĐÃ SỬA LẠI PHIÊN BẢN SDK

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.2
  supabase_flutter: ^2.9.1
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  cached_video_player_plus: ^3.0.1
  video_player: ^2.8.1
  cupertino_icons: ^1.0.8
  flutter_slidable: ^3.1.0 # Để tạo thao tác vuốt để trả lời
  pull_to_refresh: ^2.0.0 # Để tạo chức năng kéo để làm mới
  iconsax: ^0.0.8
  wakelock: ^0.6.2
  provider: ^6.1.5
  firebase_core: ^3.13.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  visibility_detector: ^0.4.0+2
  flutter_localization: ^0.3.2
  cached_network_image: ^3.4.1
  timeago: ^3.7.1
  intl: ^0.20.2
  path_provider: ^2.1.3
  path: ^1.9.0
  video_compress: ^3.1.2
  video_thumbnail: ^0.5.3
  uuid: ^4.5.1
  ffmpeg_kit_flutter_new: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  realtime_client: ^2.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/locales/en.json
    - assets/locales/vi.json