// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrCDljeEnIi9puoMki_3-pws1I66BaThY',
    appId: '1:1081669241506:web:460b02b9274479fa5665fb',
    messagingSenderId: '1081669241506',
    projectId: 'data-e74ec',
    authDomain: 'data-e74ec.firebaseapp.com',
    storageBucket: 'data-e74ec.firebasestorage.app',
    measurementId: 'G-CETJ1ER1DB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvS8Yw3MRIIygn8wG-d7VhP1jYG5F1uv8',
    appId: '1:1081669241506:android:aeda5387dceeadc15665fb',
    messagingSenderId: '1081669241506',
    projectId: 'data-e74ec',
    storageBucket: 'data-e74ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUyNdhh29-XaHI7RmRyS1v1C9abG11Kyo',
    appId: '1:1081669241506:ios:453d1658e3a36de25665fb',
    messagingSenderId: '1081669241506',
    projectId: 'data-e74ec',
    storageBucket: 'data-e74ec.firebasestorage.app',
    androidClientId: '1081669241506-lldmublsqggpilabs7tg3kfsjvgej4oi.apps.googleusercontent.com',
    iosClientId: '1081669241506-6rt6gh61nh39r2e3b0jbfjvnvso0fkop.apps.googleusercontent.com',
    iosBundleId: 'binh.dev.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUyNdhh29-XaHI7RmRyS1v1C9abG11Kyo',
    appId: '1:1081669241506:ios:453d1658e3a36de25665fb',
    messagingSenderId: '1081669241506',
    projectId: 'data-e74ec',
    storageBucket: 'data-e74ec.firebasestorage.app',
    androidClientId: '1081669241506-lldmublsqggpilabs7tg3kfsjvgej4oi.apps.googleusercontent.com',
    iosClientId: '1081669241506-6rt6gh61nh39r2e3b0jbfjvnvso0fkop.apps.googleusercontent.com',
    iosBundleId: 'binh.dev.tiktokClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrCDljeEnIi9puoMki_3-pws1I66BaThY',
    appId: '1:1081669241506:web:80d958d79f85be365665fb',
    messagingSenderId: '1081669241506',
    projectId: 'data-e74ec',
    authDomain: 'data-e74ec.firebaseapp.com',
    storageBucket: 'data-e74ec.firebasestorage.app',
    measurementId: 'G-7CWBCMBSVG',
  );

}